### ISSUE TITLE
Add retry option for 429 errors

### ISSUE THREAD

**Issue by jansroka** [ayeressian/bunnycdn-storage-deploy#42] opened 2023-07-20 11:22 UTC
I really like that the extension now (v2.1.0) uploads in parallel, what a massive improvement! However, I run into 429 errors (`Error: Error: Uploading filename.xyz has failed width status code 429.`). If one file out of a thousand files failes with an error, the entire action run fails.

Could you please add some sort of re-try logic that ensure that initially failing uploads are retried? Ideally, a specific number of times, and with exponential backoff? 

Thanks! 

Update:
BunnyCDN has a limit of 100 connections per IP (https://docs.bunny.net/reference/api-limits). Not sure if and how GH runners share IPs.

**Comment by ayeressian** [comment] 2023-09-07 12:22
Hi @jansroka, sorry for the late response. I was busy doing major refactoring. The issue is fixed in 2.2.1. Let me know if you face new issues. Thank you!

**Closed by ayeressian** 2023-09-07 12:22 UTC

**Comment by jansroka** [comment] 2023-09-14 09:18
Thank you for efforts! This is very helpful!
